

GET http://localhost:3000/web/api/arcitle HTTP/1.1
content-type: application/json

{
    "num":2,
    "page":0
}
###
GET http://localhost:3000/web/api/article/commentInfo
####
POST http://localhost:3000/web/api/article/comment

content-type: application/json
{
    "content":"文章不错哦!",
}
content-type: application/json
###
DELETE http://localhost:3000/admin/api/ads/delete HTTP/1.1
content-type: application/json
{
    id:"5e7975fda17083688fc25077"
}